DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS directors;

CREATE TABLE movies (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
year INTEGER,
director_id INTEGER,
FOREIGN KEY(director_id) REFERENCES directors(id) ON DELETE CASCADE
);

CREATE TABLE directors (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT
);
